const bodyCategories=[{name:'가슴',icon:'chest',subs:['전체','상부','중부','하부']},{name:'등',icon:'back',subs:['전체','광배근','승모근','등 중앙','척추기립근']},{name:'어깨',icon:'shoulders',subs:['전체','전면','측면','후면','회전근개']},{name:'팔',icon:'arms',subs:['전체','이두','삼두','전완']},{name:'하체',icon:'legs',subs:['전체','대퇴사두','햄스트링','둔근','종아리','내전근']},{name:'복근·코어',icon:'core',subs:['전체','상복부','하복부','복사근','코어 안정성']},{name:'전신',icon:'full-body',subs:['전체','근력','유산소','복합운동','워밍업']},{name:'스트레칭',icon:'stretch',subs:['전체','목·어깨','상체','허리','고관절','하체']}];
const movementCategories=[{name:'밀기',icon:'push',details:['전체','수평 밀기','수직 밀기','팔꿈치 펴기']},{name:'당기기',icon:'pull',details:['전체','수평 당기기','수직 당기기','팔꿈치 굽히기']},{name:'스쿼트',icon:'squat',details:['전체','양발 스쿼트','머신 스쿼트','한발 스쿼트']},{name:'힙힌지',icon:'hinge',details:['전체','데드리프트','엉덩이 펴기','햄스트링 중심']},{name:'런지',icon:'lunge',details:['전체','전진·후진','측면','고정형']},{name:'코어',icon:'brace',details:['전체','굽힘','회전','회전 저항','신전 저항','측면 안정성']},{name:'회전',icon:'rotate',details:['전체','상체 회전','고관절 회전','가동성']},{name:'이동·전신',icon:'locomotion',details:['전체','걷기·달리기','점프','운반','복합 동작']}];

const categoryIcons={
  chest:'<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M20 24c5-8 19-8 24 0"/><path d="M14 24c4 8 8 18 18 18s14-10 18-18"/><path d="M32 23v20"/><path d="M18 31h28"/></svg>',
  back:'<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M32 13v39"/><path d="M20 20c-2 11-2 22 5 31"/><path d="M44 20c2 11 2 22-5 31"/><path d="M18 28c7 4 21 4 28 0"/><path d="M22 40c5 3 15 3 20 0"/></svg>',
  shoulders:'<svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="32" cy="15" r="6"/><path d="M18 28c5-6 23-6 28 0"/><path d="M16 29c-6 3-9 8-10 15"/><path d="M48 29c6 3 9 8 10 15"/><path d="M24 32h16"/></svg>',
  arms:'<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M19 18v17c0 8 5 13 13 13h5"/><path d="M45 20c-2 8-6 13-13 16"/><path d="M20 18c8 0 13 4 15 11"/><path d="M34 48c7 0 11-4 12-10"/></svg>',
  legs:'<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M25 14v18l-7 19"/><path d="M39 14v18l7 19"/><path d="M25 32h14"/><path d="M18 51h10"/><path d="M36 51h10"/></svg>',
  core:'<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M24 14h16"/><path d="M22 22h20v27H22z"/><path d="M32 22v27"/><path d="M22 31h20"/><path d="M22 40h20"/></svg>',
  'full-body':'<svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="32" cy="12" r="6"/><path d="M32 18v22"/><path d="M18 27h28"/><path d="M32 40l-10 13"/><path d="M32 40l10 13"/></svg>',
  stretch:'<svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="23" cy="15" r="5"/><path d="M23 21c6 7 13 11 24 13"/><path d="M22 31l-8 17"/><path d="M29 34l-1 18"/><path d="M14 48h16"/></svg>',
  push:'<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M15 33h25"/><path d="M40 21l12 12-12 12"/><path d="M16 21v24"/></svg>',
  pull:'<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M49 33H24"/><path d="M24 21 12 33l12 12"/><path d="M48 21v24"/></svg>',
  squat:'<svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="33" cy="12" r="5"/><path d="M30 19l-7 15 14 4"/><path d="M23 34l-7 15"/><path d="M37 38l9 12"/><path d="M16 49h13"/><path d="M42 50h9"/></svg>',
  hinge:'<svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="23" cy="12" r="5"/><path d="M24 18l18 13"/><path d="M42 31l-9 19"/><path d="M25 25l-7 24"/><path d="M14 49h26"/></svg>',
  lunge:'<svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="31" cy="12" r="5"/><path d="M31 18l-4 17"/><path d="M27 35l-13 13"/><path d="M27 35h20"/><path d="M14 48h13"/><path d="M45 35l6 13"/></svg>',
  brace:'<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M25 15h14"/><path d="M23 23h18v25H23z"/><path d="M17 31l6 5"/><path d="M47 31l-6 5"/><path d="M32 23v25"/></svg>',
  rotate:'<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M44 21a17 17 0 0 0-27 8"/><path d="M17 20v9h9"/><path d="M20 43a17 17 0 0 0 27-8"/><path d="M47 44v-9h-9"/></svg>',
  locomotion:'<svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="30" cy="12" r="5"/><path d="M31 18l-8 13 12 8"/><path d="M35 39l11 10"/><path d="M23 31l-8 18"/><path d="M37 24l10 4"/></svg>'
};
function iconMarkup(item){return `<span class="category-icon">${categoryIcons[item.icon]||''}</span>`}

const videos=[{id:1,title:'DEMIC 운동 Shorts',exerciseName:'운동 자세',bodyPart:'전신',subBodyPart:'전체',movementPattern:'이동·전신',movementDetail:'복합 동작',equipment:'기타',difficulty:'확인 필요',youtubeId:'BkhOFoTvNZM',description:'사용자가 제공한 DEMIC Shorts 영상입니다. 영상 제목과 정확한 운동 분류는 실제 내용을 확인한 뒤 수정할 수 있습니다.',real:true},{id:2,title:'벤치프레스 자세 교정',exerciseName:'벤치프레스',bodyPart:'가슴',subBodyPart:'중부',movementPattern:'밀기',movementDetail:'수평 밀기',equipment:'바벨',difficulty:'초급',youtubeId:null,description:'UI 테스트용 등록 예정 항목입니다.',real:false},{id:3,title:'인클라인 벤치프레스',exerciseName:'인클라인 벤치프레스',bodyPart:'가슴',subBodyPart:'상부',movementPattern:'밀기',movementDetail:'수평 밀기',equipment:'바벨',difficulty:'초급',youtubeId:null,description:'UI 테스트용 등록 예정 항목입니다.',real:false},{id:4,title:'랫풀다운 자세',exerciseName:'랫풀다운',bodyPart:'등',subBodyPart:'광배근',movementPattern:'당기기',movementDetail:'수직 당기기',equipment:'머신',difficulty:'초급',youtubeId:null,description:'UI 테스트용 등록 예정 항목입니다.',real:false},{id:5,title:'스쿼트 기본 자세',exerciseName:'스쿼트',bodyPart:'하체',subBodyPart:'대퇴사두',movementPattern:'스쿼트',movementDetail:'양발 스쿼트',equipment:'바벨',difficulty:'초급',youtubeId:null,description:'UI 테스트용 등록 예정 항목입니다.',real:false},{id:6,title:'루마니안 데드리프트',exerciseName:'루마니안 데드리프트',bodyPart:'하체',subBodyPart:'햄스트링',movementPattern:'힙힌지',movementDetail:'햄스트링 중심',equipment:'바벨',difficulty:'중급',youtubeId:null,description:'UI 테스트용 등록 예정 항목입니다.',real:false}];
let favorites=JSON.parse(localStorage.getItem('fitclipFavorites')||'[]');let recent=JSON.parse(localStorage.getItem('fitclipRecent')||'[]');let currentBody='전체',currentSubBody='전체',currentMovement='전체',currentMovementDetail='전체',currentVideo=null,previousView='homeView',savedMode='favorites';
const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
function saveLocal(){localStorage.setItem('fitclipFavorites',JSON.stringify(favorites));localStorage.setItem('fitclipRecent',JSON.stringify(recent))}function isFavorite(id){return favorites.includes(id)}
function go(viewId){const current=$('.view.active')?.id;if(viewId==='detailView'&&current)previousView=current;$$('.view').forEach(v=>v.classList.toggle('active',v.id===viewId));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.go===viewId));if(viewId==='savedView')renderSaved();window.scrollTo({top:0,behavior:'smooth'})}
function categoryCard(item,type){const btn=document.createElement('button');btn.className='category-card';btn.innerHTML=`${iconMarkup(item)}<b>${item.name}</b>`;btn.addEventListener('click',()=>{if(type==='body'){currentBody=item.name;currentSubBody='전체';renderBody();go('bodyView')}else{currentMovement=item.name;currentMovementDetail='전체';renderMovement();go('movementView')}});return btn}
function createVideoCard(video){const el=document.createElement('article');el.className='video-card';const thumb=video.youtubeId?`https://img.youtube.com/vi/${video.youtubeId}/hqdefault.jpg`:'';el.innerHTML=`<button class="card-main"><div class="thumb">${thumb?`<img src="${thumb}" alt=""><span class="play">▶</span>`:'<span class="play">＋</span>'}</div><div class="card-copy"><h3>${video.title}</h3><p>${video.bodyPart} · ${video.subBodyPart}</p><p>${video.movementPattern} · ${video.equipment}</p></div></button><button class="favorite-btn ${isFavorite(video.id)?'active':''}" aria-label="즐겨찾기">${isFavorite(video.id)?'★':'☆'}</button>`;el.querySelector('.card-main').addEventListener('click',()=>openDetail(video));el.querySelector('.favorite-btn').addEventListener('click',(e)=>{e.stopPropagation();toggleFavorite(video.id);refreshAll()});return el}
function renderList(container,list){container.innerHTML='';if(!list.length){container.innerHTML='<div class="empty">해당 조건에 등록된 영상이 없습니다.</div>';return}list.forEach(v=>container.appendChild(createVideoCard(v)))}
function renderHome(){const bodyWrap=$('#homeBodyCategories');bodyWrap.innerHTML='';bodyCategories.forEach(x=>bodyWrap.appendChild(categoryCard(x,'body')));const moveWrap=$('#homeMovementCategories');moveWrap.innerHTML='';movementCategories.forEach(x=>moveWrap.appendChild(categoryCard(x,'movement')));const recentVideos=recent.map(id=>videos.find(v=>v.id===id)).filter(Boolean).slice(0,3);renderList($('#recentList'),recentVideos.length?recentVideos:videos.slice(0,3))}
function renderBody(){const tabs=$('#bodyTabs');tabs.innerHTML='';['전체',...bodyCategories.map(x=>x.name)].forEach(name=>{const b=document.createElement('button');b.className=`chip ${currentBody===name?'active':''}`;b.textContent=name;b.onclick=()=>{currentBody=name;currentSubBody='전체';renderBody()};tabs.appendChild(b)});const sub=$('#subBodyTabs');sub.innerHTML='';const options=currentBody==='전체'?['전체']:bodyCategories.find(x=>x.name===currentBody).subs;options.forEach(name=>{const b=document.createElement('button');b.className=`chip ${currentSubBody===name?'active':''}`;b.textContent=name;b.onclick=()=>{currentSubBody=name;renderBody()};sub.appendChild(b)});const list=videos.filter(v=>(currentBody==='전체'||v.bodyPart===currentBody)&&(currentSubBody==='전체'||v.subBodyPart===currentSubBody));$('#bodyResultTitle').textContent=currentBody==='전체'?'전체 운동':`${currentBody}${currentSubBody==='전체'?'':` · ${currentSubBody}`}`;$('#bodyCount').textContent=`${list.length}개`;renderList($('#bodyVideoList'),list)}
function renderMovement(){const tabs=$('#movementTabs');tabs.innerHTML='';['전체',...movementCategories.map(x=>x.name)].forEach(name=>{const b=document.createElement('button');b.className=`chip ${currentMovement===name?'active':''}`;b.textContent=name;b.onclick=()=>{currentMovement=name;currentMovementDetail='전체';renderMovement()};tabs.appendChild(b)});const details=$('#movementDetailTabs');details.innerHTML='';const options=currentMovement==='전체'?['전체']:movementCategories.find(x=>x.name===currentMovement).details;options.forEach(name=>{const b=document.createElement('button');b.className=`chip ${currentMovementDetail===name?'active':''}`;b.textContent=name;b.onclick=()=>{currentMovementDetail=name;renderMovement()};details.appendChild(b)});const list=videos.filter(v=>(currentMovement==='전체'||v.movementPattern===currentMovement)&&(currentMovementDetail==='전체'||v.movementDetail===currentMovementDetail));$('#movementResultTitle').textContent=currentMovement==='전체'?'전체 동작':`${currentMovement}${currentMovementDetail==='전체'?'':` · ${currentMovementDetail}`}`;$('#movementCount').textContent=`${list.length}개`;renderList($('#movementVideoList'),list)}
function openDetail(video){currentVideo=video;recent=[video.id,...recent.filter(id=>id!==video.id)].slice(0,20);saveLocal();$('#detailHeader').textContent=video.exerciseName;$('#detailTitle').textContent=video.title;$('#detailDescription').textContent=video.description;const tags=[video.bodyPart,video.subBodyPart,video.movementPattern,video.movementDetail,video.equipment,video.difficulty];$('#detailTags').innerHTML=tags.map((t,i)=>`<span class="tag ${i===0?'brand':''}">${t}</span>`).join('');const wrap=$('#playerWrap');if(video.youtubeId){wrap.innerHTML=`<iframe src="https://www.youtube.com/embed/${video.youtubeId}" title="${video.title}" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>`;$('#youtubeLink').href=`https://youtube.com/shorts/${video.youtubeId}`;$('#youtubeLink').style.display='block'}else{wrap.innerHTML='<div class="placeholder-player"><div class="play-circle">＋</div><p>실제 DEMIC 영상 등록 예정</p></div>';$('#youtubeLink').removeAttribute('href');$('#youtubeLink').style.display='none'}updateDetailFavorite();go('detailView')}
function updateDetailFavorite(){const b=$('#detailFavorite');b.textContent=currentVideo&&isFavorite(currentVideo.id)?'★':'☆';b.classList.toggle('active',currentVideo&&isFavorite(currentVideo.id))}function toggleFavorite(id){favorites=isFavorite(id)?favorites.filter(x=>x!==id):[id,...favorites];saveLocal();updateDetailFavorite()}function renderSaved(){const ids=savedMode==='favorites'?favorites:recent;renderList($('#savedList'),ids.map(id=>videos.find(v=>v.id===id)).filter(Boolean))}function refreshAll(){renderHome();renderBody();renderMovement();renderSaved()}
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));$('#detailBack').addEventListener('click',()=>go(previousView));$('#detailFavorite').addEventListener('click',()=>{if(currentVideo){toggleFavorite(currentVideo.id);refreshAll()}});$$('.saved-tab').forEach(b=>b.addEventListener('click',()=>{savedMode=b.dataset.saved;$$('.saved-tab').forEach(x=>x.classList.toggle('active',x===b));renderSaved()}));$('#homeSearch').addEventListener('input',(e)=>{const q=e.target.value.trim().toLowerCase();if(!q){renderHome();return}const list=videos.filter(v=>Object.values(v).join(' ').toLowerCase().includes(q));renderList($('#recentList'),list)});
let deferredPrompt;window.addEventListener('beforeinstallprompt',(e)=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true});if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'))}refreshAll();
